### ISSUE TITLE
update travis job

### ISSUE THREAD

**Issue by stevemart** [IBM/Hackernews-NLU#14]
the current job tries to deploy the app, but let's make it simple and just build the app.

**Comment by ibm-jason** [comment]
@stevemart when you say, "build the app" do you mean building it locally? i.e running the app inside a local docker container (for example) ?

**Comment by stevemart** [comment]
@ibm-jason i mean just run `swift build` on the code base and making sure it doesn't implode

**Comment by ibm-jason** [comment]
@stevemart sounds good and yes, feel free to add me to the PR- I'd like to see what you come up with. I can also say that I'm not a swift expert either, so honestly I'm looking for more "good first issues" to tackle. 😄

**Comment by stevemart** [comment]
@ibm-jason see PR #17
